# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
